name: solar
on:
  workflow_dispatch:
env:
  MONGO_URI: "mongodb+srv://cluster0.gdmobq1.mongodb.net/"
  MONGO_USERNAME: amu
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  ATLSE_API_KEY: ${{ secrets.ATLAS_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup platform
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install dependencies
        run: npm install
      - name: test
        run: npm test